In [ ]:
using SymPy

In [177]:
function Newton(f,x0)
    x=Sym("x") # Se toma a x como una variable simbolica
    df = diff(f(x),x) # Derivada de la funcion
    dfJ=lambdify(df,[x]) # Se convierte la derivada como una funcion de Julia
    x = x0 # Condicion inicial
    list = zeros(200) # Se define una lista donde se guardaran las iteraciones
    list[1]=x0 # Primer valor en la lista es la condicion inicial
    for i in 2:200 
       x = x - f(x)/dfJ(x) # Metodo de Newton
       list[i] = x # Se guarda el valor de x en la lista
    end
    return list
end

Newton (generic function with 1 method)

In [ ]:
x1 = Newton(f,0.1);

In [ ]:
x2 = Newton(f,0.5);

In [ ]:
x3 = Newton(f,-0.3);

In [ ]:
x4 = Newton(f,2);

In [ ]:
using PyPlot

In [ ]:
x=linspace(-2,2,500);

In [ ]:
y=x.^3-x.^2-x-1;

In [ ]:
grid(true)
title("\$ x^3-x^2-x-1 \$")
plot(x,y);

In [ ]:
fig, ax=subplots()
ax[:plot](x1, "r-", linewidth=1.5, label=0.1)
ax[:plot](x2,"b-",linewidth=1.5,label=0.5)
ax[:plot](x3,"g-",linewidth=1.5,label=-0.3)
ax[:plot](x4,"c-")
ax[:grid](true)
ax[:legend](loc="upper right")

In [ ]:
plot(x1,color="r",label=0.1)
plot(x2,color="b",label=0.5)
plot(x3,color="g",label=-0.3)
plot(x4,color="c",label=2.0)
grid(true)
legend(loc="upper right")
show();

In [184]:
function Newton2(f,x0)
    list = Newton(f,x0);
    eps = 10e-8
    list2 = []
    a = 0
    for i = 1:length(x0)
        if abs(f(list[i])) <= eps && list[i] != a
            push!(list2,list[i])
            a = list[i]
        end
    end
    return list2
end

Newton2 (generic function with 1 method)

In [167]:
10e-8

1.0e-7

In [113]:
g(x)=9x^5-x^4

g (generic function with 1 method)

In [132]:
x=linspace(-2.0,2.0,100);

In [114]:
grid(true),plot(x,g.(x))

(nothing, Any[PyObject <matplotlib.lines.Line2D object at 0x7f023df914a8>])

In [185]:
Newton2.(g,x)

100-element Array{Array{Any,1},1}:
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 ⋮    
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]
 Any[]

In [164]:
g(0.1111)

-1.523548331041507e-8

In [148]:
last(d)

0-element Array{Any,1}

In [120]:
c = []

0-element Array{Any,1}

In [121]:
push!(c,1)

1-element Array{Any,1}:
 1

In [125]:
push!(c,3)

2-element Array{Any,1}:
 1
 3

In [140]:
push!(c,-2)

3-element Array{Any,1}:
  1
  3
 -2

In [158]:
list = []
for i in 1:20
   if mod(i,2) == 0 && i != 18
        push!(list,i)
   end
end
return list

9-element Array{Any,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 20